name: Test

on:
  push:
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-20.04
    env:
      CC: gcc
    steps:
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true
      - name: Checkout v-tree-sitter
        uses: actions/checkout@v3
        with:
          path: v_tree_sitter
      - name: Move repo to ~/.vmodules/v_tree_sitter
        run: mv v_tree_sitter ~/.vmodules/v_tree_sitter
      - name: Run tests
        run: v test ~/.vmodules/v_tree_sitter

  test-macos:
    runs-on: macos-latest
    env:
      CC: clang
    steps:
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true
      - name: Checkout v-tree-sitter
        uses: actions/checkout@v3
        with:
          path: v_tree_sitter
      - name: Move repo to ~/.vmodules/v_tree_sitter
        run: mv v_tree_sitter ~/.vmodules/v_tree_sitter
      - name: Run tests
        run: v test ~/.vmodules/v_tree_sitter


  test-windows:
    runs-on: windows-latest
    env:
      CC: msvc
    steps:
      - uses: msys2/setup-msys2@v2

      - name: Echo HOME
        run: echo $HOME

      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - name: Checkout v-tree-sitter
        uses: actions/checkout@v3
        with:
          path: v_tree_sitter

      - name: Move repo to ~/.vmodules/v_tree_sitter
        run: |
          Move-Item -Verbose -Path v_tree_sitter -Destination "$HOME\.vmodules\v_tree_sitter"

      - name: Run tests
        run: v test "$HOME/.vmodules/v_tree_sitter"
